version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "cargo"
    directory: "/strobe"
    # Check for updates every Monday
    schedule:
      interval: "weekly"