name: Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    steps: []
#    - name: release-plz
#      uses: MarcoIeni/release-plz-action@v0.5.2
            