name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cd strobe; cargo fmt --check --verbose
    - name: Lint
      run: cd strobe; cargo clippy
    - name: Build
      run: cd strobe; cargo build --verbose
    - name: Run tests
      run: cd strobe; cargo test --verbose
    - name: Test no-std
      run: |
        cd test_no_std
        rustup target add thumbv7em-none-eabihf
        rustup toolchain install nightly
        cargo +nightly build --verbose
